config/routes.rb
ManybotsLocal::Application.routes.draw do

  match "/dashboard/day/:year/:month/:day", :to => "dashboard#day", :as => 'day'
  match "/agenda", :to => "calendar#today", :as => 'agenda'
  
  match "/collection/:id", :to => 'aggregations#filter', :as => 'collection'
  
  match 'analytics', :to => 'filters#new', :as => 'analytics'
  
  match 'reset_api_token', :to => 'dashboard#reset_user_token', :as => 'reset_api_token'
  
  resources :items
  
  resources :people do
    member do
      post 'highjack'
      post 'release'
    end
  end
  
  resources :library, :controller => :aggregations do
    collection do 
      get 'autocomplete'
    end
  end
  
  resources :predictions
  
  resources :search do
    collection do
      get 'everything', :action => 'everything'
      get 'everything/:query', :action => 'everything'
    end
  end
  
  resources :calendar do
    collection do
      get 'today'
      get 'today/:what', :action => 'today'
      get 'tomorrow'
      get 'tomorrow/:what', :action => 'tomorrow'
      get 'yesterday'
      get 'yesterday/:what', :action => 'yesterday'
      get 'day'
      get 'day/:year/:month/:day', :action => :day
      get 'day/:year/:month/:day/:what', :action => :day
    end
  end

  resources :visualizations do
    member do
      post 'install'
      post 'uninstall'
    end
  end
  resources :contacts do 
    collection do
      get 'botshop'
      get 'thanks'
    end
  end

  resources :aggregations do
    member do
      get 'bundle'
      get 'activities'
      get 'aggregates'
      get 'bundle_aggregates'
      get 'notifications'
      get 'predictions'
    end
  end
  
  resources :notifications do
    member do
      post 'toggle_read'
    end
    collection do
      get 'all'
    end
  end
  
  resources :bundles do 
    member do
      get 'sparkline'
      get 'share'
      post 'add_filter'
      post 'remove_filter'
    end
  end
  
  resources :activities do
    collection do
      post 'filter'
      post 'bundle'
      get 'current'
    end
  end

  resources :oauth_clients
  
  resources :apps
  
  resources :filters do
    member do
      post 'add_to_bundle'
      post 'remove_from_bundle'
    end
  end
  
  
  resources :dashboard do
    collection do
      get 'impact'
    end
  end
  
  
  match '/me', :to => 'activities#me', :as => :me
    
  match '/api', :to => 'welcome#api', :as => :api
  match '/developers', :to => 'welcome#developers', :as => :developers
  match '/developers/rails', :to => 'welcome#rails'

  match '/oauth/test_request',  :to => 'oauth#test_request',  :as => :test_request

  match '/oauth/token',         :to => 'oauth#token',         :as => :token

  match '/oauth/access_token',  :to => 'oauth#access_token',  :as => :access_token

  match '/oauth/request_token', :to => 'oauth#request_token', :as => :request_token

  match '/oauth/authorize',     :to => 'oauth#authorize',     :as => :authorize

  match '/oauth/revoke',     :to => 'oauth#revoke',     :as => :revoke

  match '/oauth',               :to => 'oauth#index',         :as => :oauth
  
  root :to => "welcome#index"
  
  mount Resque::Server.new, :at => "/resque"
  
end

app/controllers/visualizations_controller.rb
class VisualizationsController < ApplicationController
  before_filter :authenticate_user!
  
  def index
    VisualizationApp.load_all
    @installed_applications = current_user.installed_applications
    @visualizations = ClientApplication.visualizations
  end
  
  def install
    installed = InstalledApplication.find_or_initialize_by_user_id_and_client_application_id(current_user.id, params[:id])
    if installed.new_record?
      installed.in_library = installed.client_application.in_library
      installed.in_menu = installed.client_application.in_menu
      installed.is_default = false
      installed.save
      redirect_to visualization_path(installed.client_application.id), notice: "#{installed.client_application.name} installed."
    else
      redirect_to visualizations_path, alert: 'View was already installed.'
    end
  end
  
  def uninstall
    installed = InstalledApplication.find_or_initialize_by_user_id_and_client_application_id(current_user.id, params[:id])
    installed.destroy
    redirect_to visualizations_path, notice: "#{installed.client_application.name} uninstalled."
  end
  
  def show
    @inline = false
    if params[:aggregation_id].present?
      @inline = true
      session.delete :current_aggregations
      session[:current_aggregation] = params[:aggregation_id] 
    else
      session.delete :current_aggregation
    end
    
    if params[:bundle_id].present?
      @inline = true
      session.delete :current_aggregation
      session[:current_aggregations] = CGI.unescape params[:bundle_id] 
    else
      session.delete :current_aggregations
    end
    
    @visualization = ClientApplication.where(:app_type => 'Visualization').where(:id => params[:id]).first
    logger.info "SESSION #{session.inspect}"
  end
  
  def new
    @visualization = current_user.client_applications.new
    @visualization.app_type = 'Visualization'
  end
  
  def create
    @visualization = current_user.client_applications.build(params[:client_application])
    
    if @visualization.save
      flash[:notice] = "Visualization created."
      redirect_to :action => "show", :id => @visualization.id
    else
      render :action => "new"
    end
  end
  
  def update
    @visualization = ClientApplication.find(params[:id])
    if @visualization.update_attributes(params[:client_application])
      flash[:notice] = "Visualization updated."
      redirect_to :action => "show", :id => @visualization.id
    else
      render :action => "edit"
    end
  end
  
  
  def edit
    @installed_application = InstalledApplication.find_by_user_id_and_client_application_id(current_user.id, params[:id])
    @visualization = @installed_application.client_application
  end
  
  def destroy
    @visualization = ClientApplication.find(params[:id])
    @visualization.destroy
    redirect_to visualizations_path, :notice => 'Visualization deleted.'
  end
end

app/helpers/visualizations_helper.rb
module VisualizationsHelper
end

app/views/visualizations/_form.html.haml
= error_messages_for @visualization

= form_for @visualization, :url => @visualization.new_record? ? visualizations_path : visualization_path(@visualization), :html => {:class => 'hform largeform clearfix'} do |f|

  %p.field
    %label{:for=>"client_application_name"} Visualization Name*
    = f.text_field :name 

  %p.select
    %label{:for=>"client_application_category"} Category
    = f.select :category, ClientApplication::CATEGORIES

  = f.hidden_field :app_type, :value => 'Visualization'

  %p.field
    %label{:for=>"client_application_description"} Description*
    = f.text_area :description, :rows => 4
  
  %p.field
    %label{:for=>"client_application_url"} Visualization URL*
    = f.text_field :url
    
  %p.field.clearfix
    %label{:for=>"screenshot"} 
      Screenshot URL*
      %br
      %span.meta Size: 512x240
    = f.text_field :screenshot
  
    
  %h3 Developer info

  %p.field  
    %label{:for=>"client_application_developer_name"} Developer name*
    = f.text_field :developer_name, :value => (f.object.try(:developer_name) || current_user.name)

  %p.field  
    %label{:for=>"client_application_developer_url"} Developer URL*
    = f.text_field :developer_url
  

  %p.button.save
    = f.submit 'Save'

app/views/visualizations/edit.html.erb
<div class="clearfix">
  <div style="float:left;">
    <%= image_tag @visualization.screenshot, :width => 340, :style => 'margin: 0 60px 0 0px;' %>
  </div>

  <div class="">
    <h4 class="special-title">
      <%= link_to @visualization.name, visualization_path(@visualization.id) %> 
      <span class="meta">
        by <%= link_to @visualization.developer_name, @visualization.developer_url %>
      </span>
    </h4>


    <p><%= @visualization.description %></p>
    <p style="">
      <span style="text-transform: uppercase;padding-right: 10px; font-size: 9px;">
        Display
      </span>
      <%- if @visualization.in_menu? -%>
        <span class="menu-icon">Menu</span>
      <%- end -%>
      <%- if @visualization.in_library? -%>
        <span class="library-icon">Library</span>
      <%- end -%>
      <br>
      <span style="text-transform: uppercase;padding-right: 10px; font-size: 9px;">
        Objects
      </span>
      <%- @visualization.target_objects.split(',').each do |obj| -%>
        <span class="visu-obj-target"><%= obj %></span>
      <%- end if @visualization.target_objects -%>                  
    </p>

    <p>
      <%= link_to 'Uninstall', uninstall_visualization_path(@visualization.id), method: 'post', confirm: 'Are you sure?' %>
    </p>
  </div>
</div>

app/views/visualizations/index.html.erb
<div class="">
  <div class="">
    <div class="clearfix" style="padding: 5px; height: 35px; border-bottom: 1px solid #ddd; padding-bottom: 12px;">
      <h1 class="page-title" style="float:left;padding-top:4px;">Views</h1>
      <div style="width:110px; margin-right: 30px; float: right;">
        <p class="button save" style="height: 33px;"><%= link_to 'Add more', new_visualization_path %></p>
      </div>
    </div>
    
    <div class="box-content">
      <ul style="margin: 12px 0;">
        <%- if @visualizations.any? -%>
          <%- @visualizations.each do |visu| -%>
            <li class="clearfix" style="margin: 12px 0; padding: 10px 0; border-bottom: 1px solid #ddd">
              <div style="float:left;width: 400px;" class="clearfix">
                <%= image_tag visu.screenshot, :width => 340, :style => 'margin: 0 60px 0 10px;' %>
              </div>
              <div style="float:left;width: 400px;" class="clearfix">
                <h4 class="special-title">
                  <%= link_to visu.name, visualization_path(visu.id) %> 
                  <span class="meta">
                    by <%= link_to visu.developer_name, visu.developer_url %>
                  </span>
                </h4>
                <p><%= visu.description %></p>
                <p style="clearfix">
                  <span style="text-transform: uppercase;padding-right: 10px; font-size: 9px;">
                    Display
                  </span>
                  <%- if visu.in_menu? -%>
                    <span class="menu-icon">Menu</span>
                  <%- end -%>
                  <%- if visu.in_library? -%>
                    <span class="library-icon">Library</span>
                  <%- end -%>
                  <br>
                  <span style="text-transform: uppercase;padding-right: 10px; font-size: 9px;">
                    Objects
                  </span>
                  <%- visu.target_objects.split(',').each do |obj| -%>
                    <span class="visu-obj-target"><%= obj %></span>
                  <%- end if visu.target_objects -%>                  
                </p>

                <%- unless visu.installed_by_user?(current_user.id) -%>
                  <p class="button save" style="width: 100px; float:left; height: 33px;">
                    <%= link_to 'Install', install_visualization_path(visu.id), method: 'post'%>
                  </p>
                <%- else -%>
                  <p style="float:left;"><%= link_to 'Manage', edit_visualization_path(visu) %></p>
                <%- end -%>
              </div>
            </li>
          <%- end -%>
        <%- else -%>
          <li>Create your own HTML 5 visualizations of your data!</li>
        <%- end -%>
      </ul>
    </div>
  </div>
</div>

app/views/visualizations/new.html.erb
<h1 class="page-title" style="">
  Adding more views is easy!
</h1>

<div class="box clearfix">
  <div class="box-content clearfix" style="padding-bottom: 5px;">
    <%= image_tag 'icons/github.png', width: 120, align: 'left', style:'margin-right: 40px;'%>
    <h4 class="page-title">Check out the catalogue </h4>
    <p>We encourage every one to contribute their views to the Manybots Views Catalogue page, on the GitHub's repository page.</p>
    <p class="medium save button" style="float:left; width: 100px; height: 33px;">
      <a href="https://github.com/manybots/manybots/wiki/Applications-Catalogue" class="go-to-app">Go now →</a>
    </p>
  </div> 
</div>


<div class="box clearfix">
  <div class="box-content clearfix" style="padding-bottom: 5px;">
    <%= image_tag 'icons/html5.png', width: 120, align: 'left', style:'margin-right: 40px;'%>
    <h4 class="page-title">Create your own with HTML, CSS and JS</h4>
    <p>
      It only takes a few lines of code to get started, and you don't need anything fancy: just a plain old HTML file!
    </p>
    <p class="medium save button" style="float:left; width: 100px; height: 33px;">
      <a href="https://github.com/manybots/manybots/wiki/Create-a-HTML5-app">Tutorial →</a>
    </p>
    
  </div> 
</div>


<div class="box clearfix">
  <div class="box-content clearfix" style="padding-bottom: 5px;">
    <%= image_tag 'icons/rails.png', width: 120, align: 'left', style:'margin-right: 40px;'%>
    <h4 class="page-title">Bundle them with your apps</h4>
    <p>
      Why not propose an app + a full-blown visualization to your users, instead of just one or the other? Follow the two parts of the Getting Started with Apps tutorial!
    </p>
    <p class="medium save button" style="float:left; width: 100px; height: 33px;">
      <a href="https://github.com/manybots/manybots/wiki/Creating-Apps">Tutorial →</a>
    </p>
    
  </div> 
</div>



<!-- <div class="main-content">
  <div class="box">
    <div class="box-content">
      <h1>New visualization</h1>
      <%= render :partial => 'form' %>
    </div> 
  </div>
</div> -->

app/views/visualizations/show.html.erb
<%- unless @inline -%>
  <p style="float:right;"><%= link_to 'Manage', edit_visualization_path(@visualization.id) %></p>
  <h4 id="visualization-header" class="page-title">
    <%= @visualization.name %>
    <span class="meta">by <%= link_to @visualization.developer_name, @visualization.developer_url %></span>
  </h4>  
  <hr>
<%- end -%>

<iframe src="<%= @visualization.url %>" style="width:100%; height: 800px;">
  
</iframe>