config/routes.rb
ManybotsLocal::Application.routes.draw do

  match "/dashboard/day/:year/:month/:day", :to => "dashboard#day", :as => 'day'
  match "/agenda", :to => "calendar#today", :as => 'agenda'
  
  match "/collection/:id", :to => 'aggregations#filter', :as => 'collection'
  
  match 'analytics', :to => 'filters#new', :as => 'analytics'
  
  match 'reset_api_token', :to => 'dashboard#reset_user_token', :as => 'reset_api_token'
  
  resources :items
  
  resources :people do
    member do
      post 'highjack'
      post 'release'
    end
  end
  
  resources :library, :controller => :aggregations do
    collection do 
      get 'autocomplete'
    end
  end
  
  resources :predictions
  
  resources :search do
    collection do
      get 'everything', :action => 'everything'
      get 'everything/:query', :action => 'everything'
    end
  end
  
  resources :calendar do
    collection do
      get 'today'
      get 'today/:what', :action => 'today'
      get 'tomorrow'
      get 'tomorrow/:what', :action => 'tomorrow'
      get 'yesterday'
      get 'yesterday/:what', :action => 'yesterday'
      get 'day'
      get 'day/:year/:month/:day', :action => :day
      get 'day/:year/:month/:day/:what', :action => :day
    end
  end

  resources :visualizations do
    member do
      post 'install'
      post 'uninstall'
    end
  end
  resources :contacts do 
    collection do
      get 'botshop'
      get 'thanks'
    end
  end

  resources :aggregations do
    member do
      get 'bundle'
      get 'activities'
      get 'aggregates'
      get 'bundle_aggregates'
      get 'notifications'
      get 'predictions'
    end
  end
  
  resources :notifications do
    member do
      post 'toggle_read'
    end
    collection do
      get 'all'
    end
  end
  
  resources :bundles do 
    member do
      get 'sparkline'
      get 'share'
      post 'add_filter'
      post 'remove_filter'
    end
  end
  
  resources :activities do
    collection do
      post 'filter'
      post 'bundle'
      get 'current'
    end
  end

  resources :oauth_clients
  
  resources :apps
  
  resources :filters do
    member do
      post 'add_to_bundle'
      post 'remove_from_bundle'
    end
  end
  
  
  resources :dashboard do
    collection do
      get 'impact'
    end
  end
  
  
  match '/me', :to => 'activities#me', :as => :me
    
  match '/api', :to => 'welcome#api', :as => :api
  match '/developers', :to => 'welcome#developers', :as => :developers
  match '/developers/rails', :to => 'welcome#rails'

  match '/oauth/test_request',  :to => 'oauth#test_request',  :as => :test_request

  match '/oauth/token',         :to => 'oauth#token',         :as => :token

  match '/oauth/access_token',  :to => 'oauth#access_token',  :as => :access_token

  match '/oauth/request_token', :to => 'oauth#request_token', :as => :request_token

  match '/oauth/authorize',     :to => 'oauth#authorize',     :as => :authorize

  match '/oauth/revoke',     :to => 'oauth#revoke',     :as => :revoke

  match '/oauth',               :to => 'oauth#index',         :as => :oauth
  
  root :to => "welcome#index"
  
  mount Resque::Server.new, :at => "/resque"
  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    if user_signed_in?
      if current_user.name.present?
        redirect_to '/calendar/today'
      else
        flash[:notice] = "Almost there. Please complete your profile before continuing."
        redirect_to '/account'
      end
    end
  end
  
  def api
  end
  
  def about
  end
  
  def tos
  end
  
  def privacy
  end
  
  def developers
  end
  
  def botshop
  end
  
  def testimonials
  end
  
  def platform
  end
  
  def rails
    render '/welcome/guides/rails'
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/_google_group.html.erb
<table border=0 style="background-color: #fff; padding: 5px;" cellspacing=0>
  <tr><td>
  <img src="http://groups.google.com/intl/en/images/logos/groups_logo_sm.gif"
         height=30 width=140 alt="Google Groups">
  </td></tr>
  <tr><td style="padding-left: 5px">
  <b>Subscribe to manybots-dev</b>
  </td></tr>
  <form action="http://groups.google.com/group/manybots-dev/boxsubscribe">
  <tr><td style="padding-left: 5px;">
  Email: <input type="text" name="email" size="10" style="width:160px">
  <input type="submit" name="sub" value="Subscribe">
  </td></tr>
</form>
  <tr><td align=right>
    <a href="http://groups.google.com/group/manybots-dev">Go to group</a>
  </td></tr>
</table>

app/views/welcome/about.html.erb
<section class="main-content">

  <h2 class="special-title">About Manybots</h2>

  <p>Manybots wants to help you <a href="http://blog.manybots.com/post/9955958271/your-personal-information-system" title="Your personal information system">take control of your personal information system</a>. To become a platform to which other platforms connect.</p>

  <p>To do so, Manybots provides:
    <ul>
      <li>A platform to centralize, visualize and re-use your activities</li>
      <li>An app catalogue for application discovery and management</li>
      <li>An API for developers and partners to connect to you</li>
      <li>Custom development services so that you can order your own apps</li>
      <li>Knowledge and discussion around these themes</li>
    </ul>
  </p>
  
  <p>
    Manybots also operates two applications: <a href="https://phown.manybots.com" title="Phown - Own your phones">Phown</a> and <a href="http://contactguru.me" title="Contact Guru - Life's a Pitch? There's an app for that.">Contact Guru</a>.
  <p>
  
    
  <p>Manybots IT Lda. is an early-stage startup operating out of Lisbon, Portugal. We have a solid web background and are setting out to help you own your digital self.</p>

  <p><a href="/contact">Get in touch!</a></p>
  
      
  <center style="margin-top: 40px;">
    <p class="button medium save sign-up" style="width: 280px;">
      <a href="/login"> Start using Manybots now!</a>
    </p>
    <p style="margin-top: -10px;"> It's quick, easy and free. Delete your account anytime.</p>
  </center>

  <h2>Still want to know more?</h2>
  
  <p>&nbsp;</p>

  <h3>A small manifesto</h3>  
    
  <p><strong>If some camera or software "recognizes" you somewhere, shouldn't it give you the option to check-in at that location?</strong></p>
  
  <p>The underpinnings of this funny question are important issues. Owning our personal information system is an opportunity we can seize now.</p>
  
  <p>The modern social enterprise is being designed to answer the following question: individuals come and go, so how do I optimize for rotation? How do I retain and share data, knowledge and sustained, eco-friendly control at the same time?</p>
  
  <p>But it is individuals who should ask the question, explore all it possibilities and invent the answer. Systems, whatever they are, should adapt to people's systems.</p>

  <h3>The exploratory video</h3>
  
  <iframe id="youtube-player" width="640" height="385" src="" frameborder="0" allowfullscreen></iframe>  

  <p>&nbsp;</p>
  
  <h3>Partners</h3>
  
  <p>
    Manybots partners with the following companies:
    <ul>
      <li><a href="http://www.waveweb2.com" title="Waveweb">Waveweb</a>, on Contact Guru for iPhone</li>
      <li><a href="http://www.tasboa.com" title="Tasboa">Tasboa</a>, on Phown for Android</li>
    </ul>
  </p>
  
  
  <h3>Manythanks</h3>

  <p>Major parts of Manybots are built using great technologies and resources made available by the community. In this section, we acknowledge some of these elements and their authors.</p>

  <ul>
    <li><a href="http://rubyonrails.com" title="Ruby on Rails">Ruby on Rails by David H. Hansson and contributors</a></li>
    <li><a href="http://www.activitystrea.ms" title="Activity Streams">Activity Streams, by authors and contributors</a></li>
    <li><a href="http://jquery.com" title="jQuery">jQuery by John Resig and contributors</a></li>
    <li><a href="http://colorpowered.com/colorbox/" title="ColorBox">ColorBox by Jack Moore</a></li>
    <li><a href="http://p.yusukekamiyamane.com" title="Fugue Icons">Fugue Icons by Yusuke Kamiyamane</a></li>
    <li><a href="http://wordpress.com" title="WordPress.com">Wordpress.com (TOS and Privacy Policy)</a></li>
  </ul>

  <p>And more open and free software. To all developers, and the following people, our manythanks:</p>

  <ul class="credits">
    <li><a href="http://andretorgal.com" title="André Torgal">André Torgal</a></li>
    <li><a href="http://waveweb2.com" title="Antonio Rosado">Antonio Rosado</a></li>
    <li><a href="http://tarpipe.com" title="Bruno Pedro">Bruno Pedro</a></li>
    <li><a href="http://mestrejoao.silvaneves.org" title="Gonçalo Catarino">Gonçalo Catarino</a></li>
    <li><a href="http://mestrejoao.silvaneves.org" title="João Neves">João Neves</a></li>
    <li><a href="http://quodis.com/about" title="Leihla Pinho">Leihla Pinho</li>
    <li><a href="http://lmjabreu.com" title="Luis Abreu">Luis Abreu</a></li>
    <li><a href="http://tasboa.com" title="Niko Roberts">Niko Roberts</a></li>
    <li><a href="http://nloureiro.com/" title="Nuno Loureiro">Nuno Loureiro</a></li>
    <li><a href="http://0x82.com" title="Ruben Fonseca">Ruben Fonseca</a></li>
    <li><a href="http://about.me/rui.aires" title="Rui Aires">Rui Aires</a></li>
    <li><a href="http://sergioveiga.com" title="Sergio Veiga">Sergio Veiga</a></li>
    <li><a href="http://quodis.com" title="Quodis">Quodis</a> and <a href="http://liberdade229.com" title="Liberdade 229">Liberdade 229</a></li>
    <li>All early testers and users!</li>
  </ul>
  
  
  

</section>

<script type="text/javascript" charset="utf-8">
  $(document).ready(function() {
    $('iframe#youtube-player').attr('src', 'http://www.youtube.com/embed/DdULQHKNjeU');
  });
</script>

app/views/welcome/about.html.haml
%center

  %h2 Track your activities. And use them.
  
  %p
    %span.highlight Manybots enables you to see into, and build upon, your daily life. 
  
  %p It allows you to capture, explore and analyze all your activities. Get to know more facts about yourself, make better decisions for your life.
  
  %p This short film explores some of the things that may arise if you start collecting your activities. It might help you figure out whether you're ready for this.
  
  <iframe id="youtube-player" width="640" height="385" src="" frameborder="0" allowfullscreen></iframe>  
  .clear

  %br

  %h2 Features

  %h3 Visualize your activities
  
  %p With lists, calendars and any other means developers come up with, see all your activities in context and don't miss a detail.

  %h3 Tag, Mix and Match
  
  %p Use tags and properties to associate activities and created focused visualization of different aspects of your life.

  %h3 A cloud of applications
  
  %p Applications are what you use to actually _do_ things, or capture the things you've done. Browse the app catalogue to find applications that fit your lifestyle and start tracking everything you want. 
  
  - unless current_user
    %p= link_to "Get started now »", login_path, :class=> 'awesome large green'
    
  %h3 Order your custom apps

  %p Looking for tools to make your life easier? Take a look at what the Bot Shop has to offer.

  - unless current_user
    %p= link_to "Bot Shop »", botshop_path, :class=> 'awesome large blue'

  %h3 Develop your own apps

  %p Conquer the frontier! Easily create applications to capture and visualize activities for yourself, and even with other people by publishing your apps on the catalogue. Hmmm... Easily as in "if you're a developer (or have access to one)".
  
  %p= link_to "Info for developers »", developers_path, :class=> 'awesome large magenta'
  
      
:javascript 
  $(document).ready(function() {
    $('iframe#youtube-player').attr('src', 'http://www.youtube.com/embed/DdULQHKNjeU');
  });


  

  <%= render 'aside' %>

app/views/welcome/api.html.haml
%style
  h1, h2, h3, h4, h5 { position: relative;}
  h1, h2, h3, h4, h5 { margin: 10px 0; }
  a.toc-top-link {
  position: absolute;
  width: 30px;
  padding: 1px;
  margin: 0 0 .7em 10px;
  top: 0;
  font-size: 10px;
  text-align: center;
  }
  #toc {
  width: 100px;
  overflow:hidden;
  }
  ol { list-style: upper-alpha;}
  ol ol { list-style: decimal;}
  ol ol ol { list-style: lower-roman;}
  ol ol ol ol { list-style: lower-alpha;}
  .to-the-left {
  float: left;
  }

.sec-content.to-the-left
  .box
    .box-content
      %h4 Manybots API
      %ol#toc

.main-content{:style => 'margin-left: 20px'}
  .box
    #api_doc.box-content

      %h1 Manybots Server API doc

      %h2 Overview

      %p Manybots' API allows developers to post and read activities from users' accounts. 

      %p The API uses <a href="http://oauth.net/" title="OAuth">OAuth</a> for authentication and deals with activities in the <a href="http://activitystrea.ms" title="Activity Streams">Activity Streams</a> 1.0 JSON format. In fact it only consumes and returns data in the JSON format.

      %p The applications you develop can be used to post activities into a user's stream, to read a user's stream, or to do both. For example, you could develop an application that tracks a user's activity in a specific Task Management application and posts them to Manybots, or create an application that fetches all the tasks on users' stream, coming from any application, and gives an overview of all tasks on all projects, on all apps.
      
      %h3 Using Activity Streams
      
      %p You opened this page in your browser. If you wanted to share that activity with the world, how would you describe it programatically?
      
      %p Activity Streams provides an answer. To make it simple:
      %ul
        %li You: the actor
        %li open: the verb
        %li this page: the object
        %li your browser: the target
      
      %p Or when you publish a post on your blog:
      %ul
        %li You: the actor
        %li post: the verb
        %li article: the object
        %li blog: the target
        
      %p The actor, verb, object and target have standardized values and properties. Manybots uses this format to allow users and developers to create and read all kinds of different activities in a unified way.
      
      %p This way, all developers have to do is make normal POST and GET requests of JSON objects that describe any activity.
      
      %p You can learn the specifics in the <a href="#activities">Activities</a> section of this documentation.
      
      %h3 Guides, examples and libraries
      
      %p Well, there isn't much yet. But there's enough to get started -- maybe you'll be able to share your experience, we'll be happy to link to your page.
      %ul
        %li <a href="/developers/rails" title="Getting started with Ruby on Rails 3.1, Devise and Omniauth">Ruby on Rails example and getting started guide</a> -- uses Rails 3.1, Devise and Omniauth
        %li Ruby - Sinatra and Warden example

      %h2 API Methods

      %h3 OAuth Authentication

      %p Before you start talking to the Manybots API, you need to register your application in order to obtain your app's OAuth tokens. 

      %p You can start by <a href="/apps">registering your application</a>. You'll need to be logged in.

      %p For the application developer, Manybots's OAuth flow works just like Twitter's, so you should be able to find a bunch of tutorials and code out there to help you get started with OAuth in your favorite language.

      %p Since Manybots allows "streaming" authentication from other Identity Providers though, Manybots users that are not already logged in when your app requests them to authenticate are likely to experience a streamed authentication flow within the Manybots authentication flow. Identities flowing. Pretty cool, huh?

      %h3 User profile

      %p When the user is authenticated, the first thing you'll probably want to do is grab their profile information from the Manybots Server in order to setup an account for them in your application.

      %p All you have to do is make a GET request to the "/me.json" endpoint. A JSON object containing the user profile information will be returned and you'll use that data to identify the user, personalize their experience with your application, and probably to provide user information when creating Activities.

      %p.important You should treat the user's ID as provided by Manybots as the user's identifier on your app (at least with regards to Manybots), since all other attributes can change.

      %h5 Endpoint

      %p Make an authenticated GET request to <pre><code>/me.json</code></pre>
      %p Content-type: application/json
   
      %h5 Request format

      %p 
        %em No parameters are needed

      %h5 Response format
    
      <script src="https://gist.github.com/1385401.js?file=user_profile_example.js"></script>

      /=# render :partial => 'welcome/api/user_profile'
  
      %h3 Activities

      %p Activities are the heart of Manybots. They are meant to be <a href="http://activitystrea.ms/specs/json/1.0/" title="JSON Activity Streams 1.0"> Activity Streams 1.0 compliant</a>.

      %p As a result, any kind of human or machine generated activity can be represented solidly in Manybots and linked back directly to the original objects of the activity, as long as they're accessible from the Web. Up to you to find the best ways to capture activities from your and other people's life.

      %p With simple POST and GET requests and some JSON parsing you'll be generating and analyzing activities in no time.
  
      %h4 Creating activities
    
      %p To create an activity in Manybots Server, you first build an activity object in your app and then post it to Manybots on behalf of a User.
    
      %p The activity object you send to Manybots will be passed back to if it was correctly saved, and the very same object will be passed to all apps that consume the activities feed of your users.
    
      %p Manybots doesn't provide an ID other than the ones you provide - you are responsible for the information you pass on to Manybots.
    
      %p The only exception to this behavior is the use of the very helpful Auto Title feature, also explained in this document.

      %h5 Endpoint 

      %p Make an authenticated POST request to <pre><code>/activities.json</code></pre>
      %p Content-type: application/json

      %h5 Request format
      
      <script src="https://gist.github.com/1385401.js?file=activity_post_example.js"></script>
      /#=raw(render :partial => 'welcome/api/activity_post_example')
    
      %h5 Response format

      %p Returns the same object. 

      %h4 Reading all activities

      %h5 Endpoint

      %p Make an authenticated GET request to /activities.json

      %h5 Request format

      %em No parameters allowed at this point.

      %h5 Response format
      
      <script src="https://gist.github.com/1385401.js?file=activity_get_example.js"></script>
      /#= raw(render :partial => 'welcome/api/activities_get_example')
    
      %h4 Auto Title feature
    
      %p One of the fundamental jobs of Activity Streams is to provide easy ways to generate the sentence that is displayed to viewers from a formatted object. In case the service dealing with an activity can't figure out how to parse it, they may use the "title" attribute as the sentence to display.
    
      %p In order to avoid over-engineering a parser and to try and simplify things for developers, Manybots Server provides a feature called Auto Title that combines both options.
    
      %h5 What it does
    
      %p Auto Title allows developers to write their "title" fields like this
      %pre
        %code
          ACTOR added an OBJECT to TARGET
      %p Manybots Server will automatically replace these upcase strings with the information contained in the activity object.
      %p If the activity has no target, you can ommit the keyword TARGET. ACTOR and OBJECT are mandatory.
    
      %p So, when posting activities, you can use the Auto Title to easily write up the sentence that will be displayed to the viewer. 
    
      %p The activity will be saved with the replaced values. The keyword structure is not saved nor passed on to other apps.
    
      %h5 How to use it
    
      %p First, when posting the activity's title attribute must have a value that complies with the structure explained above.
    
      %p Then you only need add the following attribute to the activity object:
      %pre
        %code
          { ..., "auto_title": true, ... }
    
  
      %h3 Error Handling
      %p Errors can be: 
      %ul
        %li 401 Unauthorized: The OAuth tokens may have been revoked by the user or you're not authenticating properly
        %li 422 Unprocessable entity: Your request is malformed. Field errors are returned within the response object.
        %li 406 Not acceptable: The Content-type or URL you're using to make the request isn't valid.
        %li 500 Internal server error: The Manybots Server has an error. If this should happen, please notify support.
      
        
%script
  $("#toc").tableOfContents(
  $("#api_doc"),      // Scoped to div#wrapper
  {
  startLevel: 2,    // H2 and up
  depth:      5,    // H2 through H6,
  topLinks:   true, // Add "Top" Links to Each Header
  }
  );
  

app/views/welcome/app_guide.html.haml
%h2 Example application

Manybots is about capturing and visualizing activities, so this is what your app could do: "capture" an user's activities in the wild and post them to Manybots, help users visualize and analyze activities fetched from Manybots, or both.

The idea is to make it easy for people to have *all* their activities structured in a way that allows them, and you the developers, to mix and analyze them even though they come from a potentially infinite number of apps. This should enable people to gain significant insights into their lives.

Manybots has an HTTP API, allowing it to communicate over the Web with applications written in any language.

%h3 An example?

Say that you operate a project management application. On your app, users can create and update projects, milestones and tasks; the activities are, for example, "John created Project X", or "John completed task 'Say hello to my little friend'".

So whenever John does something on your project management app, your app can send that information to Manybots.

Now say that you don't operate a project management app, but you use one. Since that application has an API and you want to capture your activities on that application and send them to Manybots, you can still create your own app that polls the project management application's API and sends the information to Manybots, translated to the format Manybots can read.

%strong Checkout the "Creating a Manybots application" guide

%h3 Types of applications

%h4 Compatible applications

Applications that exist independently of Manybots but can communicate with it are called "Compatible applications". 

%h4 Observers

Apps that exist only to observe external applications and import information into Manybots, are called "Observers". 

%h4 Visualizers

Applications that focus on reading activities from Manybots and analyzing them are called "Visualizers".

%h4 Hybrids

Apps that do a bit of everything.

%h3 Application Directory and Privacy

Manybots has an application directory that makes it easy for users to access and manage applications.

Applications you create for Manybots can be published on the application directory and shared with others, or not: it can be accessible only via its URL or you can even make it private. You are also free to charge users to use your app. It only needs to comply with the Manybots Terms of Service.

app/views/welcome/developers.html.haml
%center
  %h2.special-title Create and integrate your own apps
  %p 
    %span.highlight And publish them on the catalogue if you want
%p
.main-content
  .box
    .box-content
            
      %h2 It's easy to get started
      
      .techs.clearfix
        .clearfix
          .tech-img
            =image_tag 'icons/oauth_icon.png', :width => '80px', :height => '80px', :alt => 'OAuth icon'
          .tech-txt
            %h4 OAuth
            
            %p Use <a href="http://oauth.net" title="OAuth Website">OAuth</a> to authorize your application's requests and authenticate users. 
            
            %p 
        .clearfix
          .tech-img
            =image_tag 'icons/as-grad-64x64.png', :width => '64px', :height => '64px', :alt => 'Activity Streams icon'
          .tech-txt
            %h4 Activity Streams
            %p Use <a href="http://activitystrea.ms" title="Activity Streams Website">Activity Streams</a> to publish and read activities. 
      
      %center{:style=>"margin-top: 20px;"}
        %p.button.medium.save.sign-up{:style=>'width: 280px;'}
          %a{:href=>"/oauth_clients/new"} Register you app now!
        %p{:style=>"margin-top: -10px;"} It's painless and risk-free. Check out the <a href="/api" title="Manybots API documentation"> API documentation</a>.

      %h2 Integrate your private or commercial app

      %p &nbsp;

      %h3 Hack, hack, hack

      %p Pull in the information that you have on other apps. Build a device that reports your activities. Bring it all to one place where you can do even more.

      %p Do it for yourself, share your app privately, or request to publish the app on the catalogue.

      %h3 Integrate existing apps

      %p You have a great app that solves your user's problems. You want to give them more control over their information and you want to attract more customers. 

      %p Integrating with Manybots is as easy as integrating with any big platform out there. 
      
      
      %h2 Different types of applications  
      %p &nbsp;

      %h3 Activity observers
  
      %p 
        Use the Manybots API to store activities that you capture with your own apps, or from other apps' APIs. 
      %p   
        It's easy to register your observer and start saving activities. You can also decide whether you'll share your app with other Manybots users on the catalogue. The Manybots API relies on standard web technologies such as REST, OAuth and Activity Streams. 

      %p
        =link_to "Register your own apps", new_oauth_client_path
      %p   
        =link_to "Check out the documentation", api_path 

      %h3 Agents
  
      %p Use agents to read your activities and build upon the power of well formed data: visualizations, alert systems, integrations, federators, or any type of workflow.
  
      %p Read from the OAuth-protected REST JSON endpoint easily using the Manybots API. You can choose whether to publish your agent on the catalogue, and have other Manybots users use it, or keep it to yourself.
  
      %p
        =link_to "Register your apps", new_oauth_client_path
      %p   
        =link_to "Check out the documentation", api_path 
  
  
      %h3 Use as a login method
  
      %p You can also simply use the Manybots API to authenticate users on your website or application.
  
      %p
        =link_to "Register your apps", new_oauth_client_path
  
      %p
        =link_to "Check out the documentation", api_path 
  
      %h3 Open Source Server

      %p Built with <a href="http://rubyonrails.org" title="Ruby on Rails">Ruby on Rails 3</a>, the server is a combination of open tools, formats and practices. You can find the code and the community on the <a href="http://github.com/webcracy/manybots" title="Manybots Server">Github page</a>.

.sec-content
  =link_to "API documentation »", api_path, :class => "awesome large magenta"
  
  .box
    .box-content.clearfix
      %h4 Step by step guides
      =image_tag 'rails.png', :align => 'left', :style => 'padding: 0 20px 20px 0'
      %p
        = link_to 'Ruby on Rails Manybots Guide', '/developers/rails'
        %br
        %span.quiet
          Your first app in 15 minutes.
  .box
    .box-content
      %h4 Help and Discussion
      =render :partial => 'google_group'

app/views/welcome/index.html.haml
.center{:style => 'text-align: center'}
  %h1{:style => 'font-family: Helvetica, Arial, Sans; font-size: 40px; text-align: center;margin-bottom:5px;'}
    Welcome to your Manybots
  %p Aggregate your digital activities from a catalogue of apps and master your digital lifestyle.


.box
  .box-content.clearfix
  
    #signup.card
    #login.card
    
:javascript
$(function() {
  $('#signup').load('/users/sign_up');
  $('#login').load('/login');
});