config/routes.rb
ManybotsLocal::Application.routes.draw do

  match "/dashboard/day/:year/:month/:day", :to => "dashboard#day", :as => 'day'
  match "/agenda", :to => "calendar#today", :as => 'agenda'
  
  match "/collection/:id", :to => 'aggregations#filter', :as => 'collection'
  
  match 'analytics', :to => 'filters#new', :as => 'analytics'
  
  match 'reset_api_token', :to => 'dashboard#reset_user_token', :as => 'reset_api_token'
  
  resources :items
  
  resources :people do
    member do
      post 'highjack'
      post 'release'
    end
  end
  
  resources :library, :controller => :aggregations do
    collection do 
      get 'autocomplete'
    end
  end
  
  resources :predictions
  
  resources :search do
    collection do
      get 'everything', :action => 'everything'
      get 'everything/:query', :action => 'everything'
    end
  end
  
  resources :calendar do
    collection do
      get 'today'
      get 'today/:what', :action => 'today'
      get 'tomorrow'
      get 'tomorrow/:what', :action => 'tomorrow'
      get 'yesterday'
      get 'yesterday/:what', :action => 'yesterday'
      get 'day'
      get 'day/:year/:month/:day', :action => :day
      get 'day/:year/:month/:day/:what', :action => :day
    end
  end

  resources :visualizations do
    member do
      post 'install'
      post 'uninstall'
    end
  end
  resources :contacts do 
    collection do
      get 'botshop'
      get 'thanks'
    end
  end

  resources :aggregations do
    member do
      get 'bundle'
      get 'activities'
      get 'aggregates'
      get 'bundle_aggregates'
      get 'notifications'
      get 'predictions'
    end
  end
  
  resources :notifications do
    member do
      post 'toggle_read'
    end
    collection do
      get 'all'
    end
  end
  
  resources :bundles do 
    member do
      get 'sparkline'
      get 'share'
      post 'add_filter'
      post 'remove_filter'
    end
  end
  
  resources :activities do
    collection do
      post 'filter'
      post 'bundle'
      get 'current'
    end
  end

  resources :oauth_clients
  
  resources :apps
  
  resources :filters do
    member do
      post 'add_to_bundle'
      post 'remove_from_bundle'
    end
  end
  
  
  resources :dashboard do
    collection do
      get 'impact'
    end
  end
  
  
  match '/me', :to => 'activities#me', :as => :me
    
  match '/api', :to => 'welcome#api', :as => :api
  match '/developers', :to => 'welcome#developers', :as => :developers
  match '/developers/rails', :to => 'welcome#rails'

  match '/oauth/test_request',  :to => 'oauth#test_request',  :as => :test_request

  match '/oauth/token',         :to => 'oauth#token',         :as => :token

  match '/oauth/access_token',  :to => 'oauth#access_token',  :as => :access_token

  match '/oauth/request_token', :to => 'oauth#request_token', :as => :request_token

  match '/oauth/authorize',     :to => 'oauth#authorize',     :as => :authorize

  match '/oauth/revoke',     :to => 'oauth#revoke',     :as => :revoke

  match '/oauth',               :to => 'oauth#index',         :as => :oauth
  
  root :to => "welcome#index"
  
  mount Resque::Server.new, :at => "/resque"
  
end

app/controllers/oauth_controller.rb
require 'oauth/controllers/provider_controller'
class OauthController < ApplicationController
  include OAuth::Controllers::ProviderController
  
  alias :logged_in? :user_signed_in?
  
  alias :login_required :authenticate_user!
  
  
  protected
  def authenticate_user(username,password)
    user = User.find_by_email params[:username]
    if user && user.valid_password?(params[:password])
      user
    else
      nil
    end
  end
  
end

app/views/oauth/authorize.html.haml
.box.clearfix
  .box-content
    %h2 Authorize access to your account

    %p

    %img{:width => 80, :height => 80, :src=> @token.client_application.app_icon_url, :style => 'float: left;margin-right: 20px;'}

    %p
      Would you like to authorize
      %strong= link_to @token.client_application.name,@token.client_application.url
      (
      = link_to @token.client_application.url,@token.client_application.url
      ) to access your account?

    %p.quiet 
      You'll be authorizing access to your name, email and avatar
      %br
      Make sure you read and agree to the 
      = (@token.client_application.name) 
      Terms of Service and Privacy Policy.
  
    = form_tag authorize_url do
      = hidden_field_tag "oauth_token", @token.token
      - if params[:oauth_callback]
        = hidden_field_tag "oauth_callback", params[:oauth_callback]

      = hidden_field_tag 'authorize', '1'
      %p.button.save
        = submit_tag 'Authorize'

app/views/oauth/authorize_failure.html.haml
%h1 You have disallowed this request

app/views/oauth/authorize_success.html.haml
%h1 You have allowed this request

%p 
  PIN: 
  = @token.verifier

app/views/oauth/oauth2_authorize.html.haml
%h1 Authorize access to your account
%p
  Would you like to authorize
  = link_to @client_application.name,@client_application.url
  (
  = link_to @client_application.url,@client_application.url
  ) to access your account?
- form_tag authorize_url do
  = hidden_field_tag "response_type", params[:response_type]
  = hidden_field_tag "client_id", params[:client_id]
  = hidden_field_tag "redirect_url", params[:redirect_url]
  = hidden_field_tag "state", params[:state]
  = hidden_field_tag "scope", params[:scope]
  = check_box_tag 'authorize'
  authorize access
  %p
    = submit_tag