config/routes.rb
ManybotsLocal::Application.routes.draw do

  match "/dashboard/day/:year/:month/:day", :to => "dashboard#day", :as => 'day'
  match "/agenda", :to => "calendar#today", :as => 'agenda'
  
  match "/collection/:id", :to => 'aggregations#filter', :as => 'collection'
  
  match 'analytics', :to => 'filters#new', :as => 'analytics'
  
  match 'reset_api_token', :to => 'dashboard#reset_user_token', :as => 'reset_api_token'
  
  resources :items
  
  resources :people do
    member do
      post 'highjack'
      post 'release'
    end
  end
  
  resources :library, :controller => :aggregations do
    collection do 
      get 'autocomplete'
    end
  end
  
  resources :predictions
  
  resources :search do
    collection do
      get 'everything', :action => 'everything'
      get 'everything/:query', :action => 'everything'
    end
  end
  
  resources :calendar do
    collection do
      get 'today'
      get 'today/:what', :action => 'today'
      get 'tomorrow'
      get 'tomorrow/:what', :action => 'tomorrow'
      get 'yesterday'
      get 'yesterday/:what', :action => 'yesterday'
      get 'day'
      get 'day/:year/:month/:day', :action => :day
      get 'day/:year/:month/:day/:what', :action => :day
    end
  end

  resources :visualizations do
    member do
      post 'install'
      post 'uninstall'
    end
  end
  resources :contacts do 
    collection do
      get 'botshop'
      get 'thanks'
    end
  end

  resources :aggregations do
    member do
      get 'bundle'
      get 'activities'
      get 'aggregates'
      get 'bundle_aggregates'
      get 'notifications'
      get 'predictions'
    end
  end
  
  resources :notifications do
    member do
      post 'toggle_read'
    end
    collection do
      get 'all'
    end
  end
  
  resources :bundles do 
    member do
      get 'sparkline'
      get 'share'
      post 'add_filter'
      post 'remove_filter'
    end
  end
  
  resources :activities do
    collection do
      post 'filter'
      post 'bundle'
      get 'current'
    end
  end

  resources :oauth_clients
  
  resources :apps
  
  resources :filters do
    member do
      post 'add_to_bundle'
      post 'remove_from_bundle'
    end
  end
  
  
  resources :dashboard do
    collection do
      get 'impact'
    end
  end
  
  
  match '/me', :to => 'activities#me', :as => :me
    
  match '/api', :to => 'welcome#api', :as => :api
  match '/developers', :to => 'welcome#developers', :as => :developers
  match '/developers/rails', :to => 'welcome#rails'

  match '/oauth/test_request',  :to => 'oauth#test_request',  :as => :test_request

  match '/oauth/token',         :to => 'oauth#token',         :as => :token

  match '/oauth/access_token',  :to => 'oauth#access_token',  :as => :access_token

  match '/oauth/request_token', :to => 'oauth#request_token', :as => :request_token

  match '/oauth/authorize',     :to => 'oauth#authorize',     :as => :authorize

  match '/oauth/revoke',     :to => 'oauth#revoke',     :as => :revoke

  match '/oauth',               :to => 'oauth#index',         :as => :oauth
  
  root :to => "welcome#index"
  
  mount Resque::Server.new, :at => "/resque"
  
end

app/controllers/oauth_clients_controller.rb
class OauthClientsController < ApplicationController
  before_filter :login_required
  before_filter :get_client_application, :only => [:show, :edit, :update, :destroy]
  
  alias :login_required :authenticate_user!
  
  def index
    redirect_to apps_path
  end

  def new
    @client_application = ClientApplication.new
  end

  def create
    @client_application = current_user.client_applications.build(params[:client_application])
    if @client_application.save
      flash[:notice] = "Registered the information successfully"
      redirect_to :action => "show", :id => @client_application.id
    else
      render :action => "new"
    end
  end
  
  def show
  end

  def edit
  end
  
  def update
    if @client_application.update_attributes(params[:client_application])
      flash[:notice] = "Updated the client information successfully"
      redirect_to :action => "show", :id => @client_application.id
    else
      render :action => "edit"
    end
  end

  def destroy
    @client_application.destroy
    flash[:notice] = "Application registration destroyed."
    redirect_to apps_path
  end
  
  private
  def get_client_application
    unless @client_application = current_user.client_applications.find(params[:id])
      flash.now[:error] = "Wrong application id"
      raise ActiveRecord::RecordNotFound
    end
  end
end

app/views/oauth_clients/_form.html.haml
=error_messages_for :client_application


%h3 Private application

%p Your application will be private and will not appear on the catalogue to other users. 

%p Get in touch with us through the Contacts page, we'll be happy to work with you to get it published.

%h3 Application info

%p.field
  %label{:for=>"client_application_name"} Application Name*
  = f.text_field :name 
%p.field  
  %label{:for=>"app_icon_url"} Application Icon URL*
  = f.text_field :app_icon_url

%p.select
  %label{:for=>"client_application_category"} Category
  = f.select :category, ClientApplication::CATEGORIES

%p.select
  %label{:for=>"client_application_category"} Application type
  = f.select :app_type, ClientApplication::APP_TYPES
  
%p.field
  %label{:for=>"client_application_description"} Description*
  = f.text_area :description, :rows => 4
  
  
%h3 Application settings

%p.field
  %label{:for=>"client_application_url"} Main Application URL*
  = f.text_field :url 

%p.field.clearfix
  %label{:for=>"client_application_callback_url"} 
    OAuth Callback URL*
    %span.meta Leave blank if your app is an HTML 5 visualization
  = f.text_field :callback_url 
  
%p.field
  %label{:for=>"client_application_support_url"} Support URL
  = f.text_field :support_url 

%h3 Developer info

%p.field  
  %label{:for=>"client_application_developer_name"} Developer name*
  = f.text_field :developer_name, :value => (f.object.try(:developer_name) || current_user.name)
  
%p.field  
  %label{:for=>"client_application_developer_url"} Developer URL*
  = f.text_field :developer_url

-#%h3 Publish this application?
-#%p.checkbox
-# f.check_box :is_public
-#%label{:for=>"client_application_is_public"} Publish this application and make it available in the application catalogue for all users
  
%h3 What kind of integration does the application offer?

%p.checkbox
  = f.check_box :offers_login
  %label{:for=>"client_application_offers_login"} Users can login to your application using their Manybots Account
  
%p.checkbox
  = f.check_box :offers_exports
  %label{:for=>"client_application_offers_exports"} Users can post their activities on your app to their Manybots Account

%p.checkbox
  = f.check_box :offers_reading
  %label{:for=>"client_application_offers_reading"} Users can visualize activities from their Manybots Account
  

app/views/oauth_clients/edit.html.haml
.main-content
  .box
    .box-content
      %h2 Edit your application
      = form_for @client_application, :url => oauth_client_path(@client_application.id), :method => :put, :html => {:class => 'hform largeform clearfix'} do |f|
        = render :partial => "form", :locals => { :f => f }

        %p.button.save
          = submit_tag "Update"
#resources
  %p
    =link_to 'Cancel', app_path(@client_application)
  %p
    =link_to 'Delete this application', oauth_client_path(@client_application), :method => :delete, :class => '', :confirm => "Are you sure you want to delete this application? There is no undo."

app/views/oauth_clients/index.html.haml
%h1 OAuth Client Applications
- unless @tokens.empty?

  %p 
    The following tokens have been issued to applications in your name
    
  %table
    %tr
      %th Application
      %th Issued
      %th &nbsp;
    - @tokens.each do |token|
      - content_tag_for :tr, token do
        %td= link_to token.client_application.name, token.client_application.url
        %td= token.authorized_at
        %td
          - form_tag revoke_path do
            = hidden_field_tag 'token', token.token
            = submit_tag "Revoke!"

%h3 Application Developers

- if @client_applications.empty?
  %p
    Do you have an application you would like to register for use with us using the <a href="http://oauth.net">OAuth</a> standard?
    You must register your web application before it can make OAuth requests to this service
- else
  %p
    You have the following client applications registered:

  - @client_applications.each do |client|
    - div_for client do
      = link_to client.name, :action => :show, :id => client.id
      = link_to 'Edit', edit_oauth_client_path(client)
      = link_to 'Delete', oauth_client_path(client), :confirm => "Are you sure?", :method => :delete
%br
%h3
  = link_to "Register your application", :action => :new

app/views/oauth_clients/new.html.haml
.main-content
  .box
    .box-content
      %h2 Register a new application

      = form_for :client_application, :url => { :action => :create }, :html => {:class => 'hform largeform clearfix'} do |f|
        = render :partial => "form", :locals => { :f => f }
        
        %p.button.save
          = submit_tag "Register"

  =link_to 'Cancel', apps_path
  

app/views/oauth_clients/show.html.haml
.main-content
  .box
    .box-content
    
      %h1= @client_application.name
    
      %p
        Publication status:
        %strong.highlight= (@client_application.is_public? ? "Public" : "Private")
      
      %h3 Display preview
      
      .box-content.apps.clearfix
        = render :partial => 'apps/app', :locals => {:app => @client_application, :the_cycle => cycle('', '')}  
      
      %h3 Application URLs

      %ul
        %li 
          Application: 
          = @client_application.url
        %li 
          Callback: 
          = @client_application.callback_url
        %li 
          Support:
          =@client_application.support_url
  

      %h3 
        OAuth details for 
        =@client_application.name
      %p
        %strong Consumer Key:
        %code=@client_application.key
      %p
        %strong Consumer Secret:
        %code=@client_application.secret 

      %p
        %strong Request Token URL
        %code
          ="http#{'s' if request.ssl?}://#{request.host_with_port}#{@client_application.oauth_server.request_token_path}"

      %p
        %strong Access Token URL
        %code
          ="http#{'s' if request.ssl?}://#{request.host_with_port}#{@client_application.oauth_server.access_token_path}"

      %p
        %strong Authorize URL
        %code
          ="http#{'s' if request.ssl?}://#{request.host_with_port}#{@client_application.oauth_server.authorize_path}"

      %p
        We support hmac-sha1 (recommended) as well as plain text in ssl mode.

%aside.sec-content

  %p
    = link_to 'Edit this app', edit_oauth_client_path(@client_application), :class => 'awesome'
  %p
    = link_to 'Back to all apps', oauth_clients_path